sudo: false
language: php
php:
  - 5.5
  - 5.6
  - nightly
env:
  - CODECLIMATE_REPO_TOKEN=d8c626969c36be4b743244deca8493ad68f69aafd6790f7da89e9d8c00c3c576

before_script:
  - composer self-update
  - composer install

script: make test
after_script: ./vendor/bin/test-reporter
